sudo: required
services:
  - docker

before_install:
  - docker build -t satishgrg23/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true satishgrg23/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-871416316160"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY